package com.oeims.services

import com.oeims.models.EventRecord
import com.oeims.models.ExamRecord
import com.oeims.models.ParticipantRecord
import com.oeims.models.SessionRecord
import java.time.Instant

object SessionReportFormatter {

    fun format(
        session: SessionRecord,
        exam: ExamRecord,
        participants: List<ParticipantRecord>,
        events: List<EventRecord>,
        generatedAt: Instant = Instant.now(),
    ): String {
        val participantsById = participants.associateBy { it.id }

        return buildString {
            appendLine("EXAM SESSION REPORT (generated by OEIMS)")
            appendLine("Generated at: $generatedAt")
            appendLine("Exam: ${exam.title}")
            appendLine("Session code: ${session.code}")
            appendLine("Status: ${session.status}")
            appendLine()

            appendSection("EXAM IDENTITY CODES")

            if (participants.isEmpty()) {
                appendLine("No participants joined this session.")
            } else {
                participants
                    .sortedBy { it.email.lowercase() }
                    .forEach { participant ->
                        appendIdentityCode(participant)
                    }
            }

            appendLine()
            appendSection("ACTIVITY")

            if (events.isEmpty()) {
                appendLine("No activity was recorded.")
            } else {
                events
                    .sortedWith(
                        compareBy<EventRecord> { it.occurredAt }
                            .thenBy { participantsById[it.participantId]?.email.orEmpty() }
                    )
                    .forEach { event ->
                        val email = participantsById[event.participantId]?.email
                            ?: "Unknown participant ${event.participantId}"

                        appendLine(
                            "[${event.occurredAt}] [${event.severity.name}] " +
                                    "$email - ${event.monitorName}: ${event.message}"
                        )
                    }
            }
        }
    }

    private fun StringBuilder.appendSection(title: String) {
        appendLine("============================================================")
        appendLine(title)
        appendLine("============================================================")
        appendLine()
    }

    private fun StringBuilder.appendIdentityCode(participant: ParticipantRecord) {
        val code = participant.examIdentityCode ?: "Not generated"
        appendLine("${participant.email.padEnd(32)} $code")
    }
}